# @format
name: web-server
services:
  nginx:
    container_name: nginx
    image: tiangolo/nginx-rtmp
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/yusufciraknet/nginx-selfsigned.crt:/etc/ssl/yusufciraknet/certs/nginx-selfsigned.crt:ro
      - ./nginx/ssl/yusufciraknet/nginx-selfsigned.key:/etc/ssl/yusufciraknet/private/nginx-selfsigned.key:ro
      - ./nginx/ssl/tumeraltunbascom/nginx-selfsigned.crt:/etc/ssl/tumeraltunbascom/certs/nginx-selfsigned.crt:ro
      - ./nginx/ssl/tumeraltunbascom/nginx-selfsigned.key:/etc/ssl/tumeraltunbascom/private/nginx-selfsigned.key:ro
    ports:
      - 443:443
      - 443:443/udp
      - 1935:1935
    networks:
      - chat-app
      - tumeraltunbascom
      - website
      - streaming-app
      - discord

networks:
  chat-app:
    external: true

  tumeraltunbascom:
    external: true

  website:
    external: true

  streaming-app:
    external: true

  discord:
    external: true
