# @format

name: tirreno-compose

services:
  tirreno:
    image: tirreno/tirreno:latest
    container_name: tirreno
    restart: unless-stopped
    ports:
      - 8585:80
    volumes:
      - tirreno_volume:/var/www/html
    networks:
      - tirreno-network
      - streaming-app

networks:
  tirreno-network:
    name: tirreno-network
    driver: bridge
  streaming-app:
    name: streaming-app
    driver: bridge

volumes:
  tirreno_volume:
