# @format

name: tirreno-compose

services:
  tirreno:
    image: tirreno/tirreno:latest
    restart: unless-stopped
    ports:
      - 8585:80
    volumes:
      - tirreno_volume:/var/www/html
    networks:
      - tirreno-network

networks:
  tirreno-network:
    name: tirreno-network
    driver: bridge

volumes:
  tirreno_volume:
