name: Publish Web Server Configuration
on:
  push:
    branches:
      - main
jobs:
  release:
    concurrency:
      group: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Web Server Configuration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd home && rm -rf yusufcirak.net-nginx && git clone https://github.com/yusuf-cirak/yusufcirak.net-nginx.git && cd yusufcirak.net-nginx && git checkout main && git pull && bash start.sh
